version: '3.9'

networks:
  fabric_net:
    external: true
    name: fabric_fabric_net

services:
  peer0_org2:
    image: hyperledger/fabric-peer:2.4.4
    hostname: peer0.org2.example.com
    environment:
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_ADDRESS=peer0.org2.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.example.com:8052  # Используем FQDN вместо 0.0.0.0
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:8051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_PEER_TLS_ENABLED=false
    volumes:
      - ./organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com:/etc/hyperledger/peer
    ports:
      - "8051:8051"
      - "8052:8052"
    networks:
      fabric_net:
        aliases:
          - peer0.org2.example.com