version: '3.9'

networks:
  fabric_net:
    external: true
    name: fabric_fabric_net

services:
  peer0_org3:
    image: hyperledger/fabric-peer:2.4.4
    hostname: peer0.org3.example.com
    environment:
      - CORE_PEER_ID=peer0.org3.example.com
      - CORE_PEER_ADDRESS=peer0.org3.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.example.com:9052  # Используем FQDN вместо 0.0.0.0
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.example.com:9051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_PEER_TLS_ENABLED=false  # Временно отключено для отладки
    volumes:
      - ./organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com:/etc/hyperledger/peer
    ports:
      - "9051:9051"
      - "9052:9052"  # Порт для chaincode
    networks:
      fabric_net:
        aliases:
          - peer0.org3.example.com